name: Release
on:
  release:
      types: [created]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
          os: [ubuntu-latest,windows-latest,macOS-latest]
          include:
            - os: windows-latest
              releasename: 'Windows'
            - os: ubuntu-latest
              releasename: 'Unix'
            - os: macOS-latest
              releasename: 'Mac'
    steps:
     - uses: actions/checkout@v4
     - uses: actions/setup-java@v4
       with:
         java-version: 25
         distribution: "temurin"
         cache: maven
     - run: mvn verify
     - uses: actions/upload-artifact@v4
       with:
           name: ${{ matrix.releasename }}
           path: 'target/release'
     - uses: AButler/upload-release-assets@v2.0
       with:
         files: 'target/release/*'
         repo-token: ${{ secrets.GITHUB_TOKEN }}
